import '../../media/media_item.dart';
import '../../models/yattee/yattee_video.dart';
import '../../mpv/mpv.dart';
import '../../services/playback_context.dart';
import '../../services/playback_initialization_types.dart';
import '../../services/yattee/yattee_stream_selector.dart';

/// Launch parameters for a YouTube (Yattee Server) session — the parallel of
/// [LiveTvSessionArgs]. A [VideoPlayerScreen] plays YouTube iff it was
/// constructed with one of these.
///
/// Unlike server-backed items there is nothing for the player to resolve:
/// the launch flow already fetched `/videos/{id}` and picked the streams,
/// so this carries the finished [YatteeStreamSelection] and the screen
/// short-circuits `PlaybackSourceResolver` with [toPlaybackContext].
class YouTubeSessionArgs {
  final YatteeVideo video;
  final YatteeStreamSelection selection;

  /// Sidecars attached at open. Every caption YouTube lists is a small
  /// WebVTT file, but auto-generated tracks can run to dozens of languages
  /// and mpv fetches each `sub-files` entry during load, so the list is
  /// capped with human-made tracks first.
  static const int maxCaptionSidecars = 12;

  const YouTubeSessionArgs({required this.video, required this.selection});

  /// The resolver output the player would otherwise have built: a direct
  /// remote source with no reporting client — there is no server to report
  /// progress to — plus the separate audio stream and the caption sidecars.
  PlaybackContext toPlaybackContext(MediaItem metadata) {
    final result = PlaybackInitializationResult(
      availableVersions: const [],
      videoUrl: selection.videoUrl,
      externalAudioUrl: selection.audioUrl,
      subtitleSidecars: captionSidecars(video.captions),
      playMethod: 'DirectPlay',
    );
    return PlaybackContext(
      metadata: metadata,
      result: result,
      sourceKind: PlaybackSourceKind.remoteDirect,
      reportingMode: PlaybackReportingMode.disabled,
      streamHeaders: selection.headers,
    );
  }

  static List<PlaybackSubtitleSidecar> captionSidecars(List<YatteeCaption> captions) {
    final ordered = [...captions.where((c) => !c.autoGenerated), ...captions.where((c) => c.autoGenerated)];
    return [
      for (final caption in ordered.take(maxCaptionSidecars))
        PlaybackSubtitleSidecar(
          // No server-side stream catalog to link back to; the sidecar is
          // its own identity.
          sourceStreamId: null,
          track: SubtitleTrack.uri(
            caption.url,
            title: caption.label.isNotEmpty ? caption.label : caption.languageCode,
            language: caption.languageCode.isNotEmpty ? caption.languageCode : null,
            codec: 'vtt',
          ),
          preload: true,
        ),
    ];
  }
}
